# Generated by Django 3.2.3 on 2021-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
